### ISSUE TITLE
Decryption error: MAC check failed

### ISSUE THREAD

**Issue by neptotech** [scaredandalone/cookiestealer#1]
Decryption error: MAC check failed
Decryption error: MAC check failed
Decryption error: MAC check failed
Decryption error: MAC check failed
Decryption error: MAC check failed
Decryption error: MAC check failed

is what i get when i run mainclient.py

**Comment by scaredandalone** [comment]
The "MAC check failed" error occurs when there's an issue with AES decryption.
For example, if you're using a different browser or operating system, the way cookies are encrypted might differ, causing the decryption to fail. 
This script was tested on Windows 10 with Google Chrome, so if you're using a different setup, you may need to adjust the code to match your environment.
